# Site settings
title: Melissa Peterson
email: melissa@petersonlcsw.com
description: > # this means to ignore newlines until "baseurl:"
  Mental health.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://petersonlicsw.com" # the base hostname & protocol for your site
twitter_username: timrpeterson
github_username:  
linkedin_username:  melissa-peterson-licsw-5b237413



# Build settings
markdown: kramdown

gems: ['jekyll-sitemap']
